# Generated by Django 4.2.3 on 2023-09-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingregistration',
            name='street_address',
        ),
        migrations.AddField(
            model_name='weddingregistration',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='best_day_for_monthly_invoice_due',
            field=models.IntegerField(blank=True, null=True, verbose_name='Melhor Dia para Vencimento dos Boletos'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='bride_and_groom_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome dos Noivos'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='bride_instagram_profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perfil Instagram da Noiva'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. Celular'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='groom_instagram_profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perfil Instagram do Noivo'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Convidados'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='spouse_cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. Celular do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='weddingregistration',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
