# Generated by Django 4.2.3 on 2023-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_weddingregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingregistration',
            name='status',
            field=models.CharField(choices=[('pré reserva', 'Pré Reserva'), ('ocupado', 'Ocupado')], default='pré reserva', max_length=15),
        ),
    ]
