# Generated by Django 4.2.3 on 2023-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_weddingregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingregistration',
            name='event_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='Data do Evento'),
        ),
    ]
