# Generated by Django 4.2.3 on 2023-07-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('user_uuid', models.UUIDField()),
                ('status', models.CharField(max_length=20)),
                ('call_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
